### ISSUE TITLE
Feature Request: Fetching Completed Tasks from Todoist

### ISSUE THREAD

**Issue by mykolakozlo** [benjypng/logseq-todoist-plugin#46]
There's an existing solution for fetching Todoist completed tasks with Obsidian. It would be great to have such a feature in Logseq.

Here's the Obsidian plugin:
https://github.com/Ledaryy/obsidian-todoist-completed-tasks.git

**Comment by benjypng** [comment]
Decided to close this as I think it can be quite unwieldy getting completed tasks since they can be quite extensive.
