### ISSUE TITLE
Issue fetching todays sub-tasks 

### ISSUE THREAD

**Issue by wkbt** [benjypng/logseq-todoist-plugin#81]
Hey! Thanks for this great plugin. I have an issue where I have 3 tasks that have a deadline by today, but only 1 is fetched through the command to retrieve today's tasks. I've found out that is due to the other 2 being sub-tasks to a task that doesn't have it's deadline by today. If I set the deadline of the main task to today, that task and its sub-tasks shows up as intended.

Is there something I've missed or is this something that could be improved?

**Comment by benjypng** [comment]
This is the intended behaviour as a sub-task needs a parent block to be nested in.
