### ISSUE TITLE
Default label not sent 

### ISSUE THREAD

**Issue by erobert-c** [benjypng/logseq-todoist-plugin#82]
Hello and first of, thanks for the plugin.

I have my workflow where I usually sort my tasks in Todoist from my inbox and move them to the right project and the right date. So I configured the plugin to have the default project set to `Inbox`, the default label set to `fromlogseq` and ticked the `sendDefaultDeadline`.

However, whenever I send a task using the slash command, I got the deadline properly set to `Today`, the task is well sent to my `Inbox`,  but I don't have the default label.
Am I missing something in the configuration?

Thanks in advance.

**Comment by benjypng** [comment]
Fixed in latest version.
