### ISSUE TITLE
Feature request: add the option to remove "scheduled" information when retrieving tasks

### ISSUE THREAD

**Issue by jonbstrong** [benjypng/logseq-todoist-plugin#83]
I would prefer a more minimal list when retrieving tasks from Todoist. 
Would it be possible to add an option to remove the scheduled info?
It would also be neat if we could have the task description as a sub bullet point rather than as a line below the task name.

**Comment by jonbstrong** [comment]
As a workaround, this ChatGPT prompt appears to work for me at the moment:

```
Take the list below and remove the following - attachments::  comments::  todoistid:: and the scheduled info. 
Also, the task description should be a sub bullet point. 

The modified output that you deliver should be in markdown so I can simply click the copy button and paste it directly into Logseq.

**Task List**
INSERT_TASK_LIST
```

**Comment by benjypng** [comment]
Fixed in latest version.

I've also went ahead to create a new issue for:

>  It would also be neat if we could have the task description as a sub bullet point rather than as a line below the task name.
