### ISSUE TITLE
sending task to todoist doesn't use previously selected project (even though it is shown in the UI)

### ISSUE THREAD

**Issue by clarsen** [benjypng/logseq-todoist-plugin#86]
Plugin version v5.1.9
Logseq version 0.10.9

Steps to reproduce:

1. restart logseq
2. Invoke "Todoist: Send Task".  The "select a project" dropdown is shown as "--- ---".
3. Select a project other than "Inbox"
4. Leave label and deadline unset
5. Send Task.  Confirm the task appears in the selected project.

Then send another task.

1. Invoke "Todoist: Send Task".  The "Select a project" dropdown shows the previously specified project.
2. Send Task.  Confirm the task appears in "Inbox" rather than the selected project.

would expect the task to be sent to the project which is shown in "select a project" dropdown.

Workaround:

1. Invoke "Todoist: Send Task".  The "Select a project" dropdown shows the previously specified project.
2. Select "--- ---" in the "Select a project" dropdown
3. Then select the desired project
4. Send Task.  Confirm the task appears in the selected project.

**Comment by benjypng** [comment]
Fixing.

**Comment by benjypng** [comment]
Fixed in latest version.
