### ISSUE TITLE
App Icon doesn't appear in Logseq

### ISSUE THREAD

**Issue by Fkaule** [benjypng/logseq-todoist-plugin#92]
I'm using Logseq 0.10.9 on MacOS 15.0.1 (24A348). I installed the Plugin via the Plugin in Logseq. I wanted to paste my test token into the app, but the plugin icon doesn't appear (also not in the unpinned list of all plugins). If I use the "/" command there are the todoist features, but I can not use them because I didn't connect my account.

**Comment by Fkaule** [comment]
sorry my fault, was looking in the wrong place :(

**Comment by lemiesz** [comment]
And what was the right place? I'm having the same problem

**Comment by Fkaule** [comment]
Settings -> Plugins -> logseq-todoist-plugin
